# Copyright n8n GmbH 2025
# SPDX-License-Identifier: MIT

# Plan-time tests for the modules/tls-self-signed submodule using mocked
# providers. Exercises the Key Vault Self-issuer contract without
# contacting Azure.
#
# Run: terraform test
#   (from this directory's parent — modules/tls-self-signed/. No
#    Azure credentials needed; the only provider is mocked.)

mock_provider "azurerm" {}

variables {
  domain_name          = "n8n.example.com"
  key_vault_id         = "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/n8ntest-shared-rg/providers/Microsoft.KeyVault/vaults/n8ntest-shared-kv"
  friendly_name_prefix = "n8ntest"
  common_tags          = { Environment = "test" }
}

run "submodule_plans_clean_with_defaults" {
  command = plan

  # The submodule's only contract output reads
  # `azurerm_key_vault_certificate.self_signed.secret_id`, which is computed
  # at apply time (Azure assigns the versioned URI). Under mock_provider
  # `secret_id` stays unknown at plan time, so the "non-empty in plan"
  # assertion (PRD AC #7) needs `override_resource` to pin a synthetic
  # plan-known value. Mirrors the n8n_helm_multi_main pattern in the root
  # module's tests/defaults.tftest.hcl and the tls-letsencrypt sibling.
  override_resource {
    target          = azurerm_key_vault_certificate.self_signed
    override_during = plan
    values = {
      secret_id = "https://n8ntest-shared-kv.vault.azure.net/secrets/n8ntest-n8n-tls/0123456789abcdef0123456789abcdef"
    }
  }

  # ── Self-signed cert (now generated by KV's Self issuer) ──────────────────
  # CN tracks `var.domain_name`. Required because the App Gateway listener
  # presents this CN to clients — a mismatch with the ingress hostname is
  # an immediate browser cert-name error. Encoded as `CN=<fqdn>` in the
  # KV cert policy's `x509_certificate_properties.subject` field.
  assert {
    condition     = azurerm_key_vault_certificate.self_signed.certificate_policy[0].x509_certificate_properties[0].subject == "CN=${var.domain_name}"
    error_message = "azurerm_key_vault_certificate.self_signed.certificate_policy.x509_certificate_properties.subject must equal CN=<var.domain_name>"
  }

  # SAN list contains the same FQDN — modern browsers (Chrome 58+) ignore
  # CN entirely and require the FQDN to appear in `dns_names` for cert-name
  # validation to pass.
  assert {
    condition     = contains(azurerm_key_vault_certificate.self_signed.certificate_policy[0].x509_certificate_properties[0].subject_alternative_names[0].dns_names, var.domain_name)
    error_message = "azurerm_key_vault_certificate.self_signed certificate_policy.x509_certificate_properties.subject_alternative_names.dns_names must contain var.domain_name"
  }

  # Validity window tracks `var.validity_period_hours` (default 8760 = 1y),
  # converted to integer months for KV's `validity_in_months` policy field
  # (730 hours ≈ 1 month). A regression here (e.g. accidentally hard-coded
  # back to a literal) would silently ignore the operator's renewal-cadence
  # preference.
  assert {
    condition     = azurerm_key_vault_certificate.self_signed.certificate_policy[0].x509_certificate_properties[0].validity_in_months == floor(var.validity_period_hours / 730)
    error_message = "azurerm_key_vault_certificate.self_signed.certificate_policy.x509_certificate_properties.validity_in_months must equal floor(var.validity_period_hours / 730)"
  }

  # KV stores the cert as an unencrypted PFX (PKCS#12) — required so
  # Application Gateway v2's KV-integration code path can consume the
  # secret URI. The legacy PEM-typed import path silently failed at AGW
  # provisioning time with a generic `InternalServerError`.
  assert {
    condition     = azurerm_key_vault_certificate.self_signed.certificate_policy[0].secret_properties[0].content_type == "application/x-pkcs12"
    error_message = "azurerm_key_vault_certificate.self_signed.certificate_policy.secret_properties.content_type must be 'application/x-pkcs12' so AGW v2 can consume the secret URI"
  }

  # KV's Self issuer is what drives the rewrite — it generates the keypair
  # in the vault and signs the cert internally, sidestepping the format
  # mismatch the legacy `hashicorp/tls` import path tripped over.
  assert {
    condition     = azurerm_key_vault_certificate.self_signed.certificate_policy[0].issuer_parameters[0].name == "Self"
    error_message = "azurerm_key_vault_certificate.self_signed.certificate_policy.issuer_parameters.name must be 'Self' (KV-native self-signed issuer)"
  }

  # ── Key Vault certificate object ──────────────────────────────────────────
  # The cert object name embeds friendly_name_prefix so callers running
  # parallel n8n stacks against a shared Key Vault don't collide on the
  # well-known `n8n-tls` literal the legacy inline path used. Mirrors the
  # tls-letsencrypt sibling's naming convention.
  assert {
    condition     = azurerm_key_vault_certificate.self_signed.name == "${var.friendly_name_prefix}-n8n-tls"
    error_message = "azurerm_key_vault_certificate.self_signed.name must be '<friendly_name_prefix>-n8n-tls'"
  }

  # The cert is imported into the caller-supplied vault — no module-
  # owned vault path here. US-012 will rely on this to wire the contract
  # into the root module's `app_gateway_tls_cert_secret_id` input.
  assert {
    condition     = azurerm_key_vault_certificate.self_signed.key_vault_id == var.key_vault_id
    error_message = "azurerm_key_vault_certificate.self_signed.key_vault_id must equal var.key_vault_id"
  }

  # ── Output contract (PRD AC #7 / US-010) ───────────────────────────────────
  # The submodule's single contract output is the versioned KV secret URI
  # the root module's App Gateway listener consumes. Under mock_provider
  # the computed `secret_id` resolves to the synthetic string pinned by
  # override_resource above — non-empty is the cleanest assertion possible
  # at plan time without reaching for the private-API `nonsensitive()`
  # work-around. The output IS sensitive (the versioned URI is enough to
  # fetch the private key for any holder of vault read), so we read the
  # resource attribute directly.
  assert {
    condition     = length(azurerm_key_vault_certificate.self_signed.secret_id) > 0
    error_message = "azurerm_key_vault_certificate.self_signed.secret_id must be non-empty in plan (the contract output the root module consumes via app_gateway_tls_cert_secret_id)"
  }
}

# ── Variable validation rejects bad input ─────────────────────────────────────
# One contract per validation rule. Each scenario sets one bad value, leaves
# the rest at the defaults block above, and asserts terraform plan is
# rejected before any provider call. Mirrors the `invalid_inputs_fail_fast_*`
# convention from the root module's tests and the tls-letsencrypt sibling's
# `rejects_*` runs.

run "rejects_malformed_domain_name" {
  command = plan

  variables {
    domain_name = "not a domain"
  }

  expect_failures = [
    var.domain_name,
  ]
}

run "rejects_malformed_key_vault_id" {
  command = plan

  variables {
    key_vault_id = "not-a-resource-id"
  }

  expect_failures = [
    var.key_vault_id,
  ]
}

run "rejects_invalid_friendly_name_prefix" {
  command = plan

  variables {
    friendly_name_prefix = "X"
  }

  expect_failures = [
    var.friendly_name_prefix,
  ]
}

run "rejects_validity_period_below_floor" {
  command = plan

  variables {
    validity_period_hours = 1
  }

  expect_failures = [
    var.validity_period_hours,
  ]
}
